tasks:
  - name: Pulling Rocket.Chat Image
    init: |
      docker pull registry.rocket.chat/rocketchat/rocket.chat:${RELEASE:-latest} &&
      exit

  - name: Pull Mongodb Image
    init: |
      docker pull docker.io/bitnami/mongodb:${MONGODB_VERSION:-4.4} &&
      exit

  - name: Install dependencies
    init: |
      cd github &&
      npm install &&
      exit

  - name: Initiate RocketChat Apps Test Env
    command: ./RCTestSetup

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addBadge: false